apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-simple
  namespace: kargo-simple
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
